// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // The installed prisma@7.9.1's config type only accepts `url` and
    // `shadowDatabaseUrl` here - no `directUrl`. That's fine: the CLI's own
    // migrate commands hang against Supabase's pooler regardless (see
    // scripts/apply-migrations.mjs), so this `url` is only used for
    // lightweight commands like `prisma migrate status`. Real migrations
    // read DIRECT_URL straight from .env, bypassing this file entirely.
    url: process.env["DATABASE_URL"],
  },
});
